import { useState, type FormEvent } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Bell, BookOpen, ChevronDown, GraduationCap, LayoutDashboard, Library, LogOut, Menu, Settings, Users, X } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useResource } from '../../hooks/useResource';
import { dashboardApi } from '../../api/management.api';
import { Avatar, SearchInput } from '../ui';

export function Brand() { return <div className="brand"><span><GraduationCap size={25} strokeWidth={2.1} /></span>Educare</div>; }
const navigation = [{ path: '/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { path: '/students', label: 'Students', icon: Users }, { path: '/classes', label: 'Classes', icon: GraduationCap }, { path: '/lecturers', label: 'Lecturers', icon: BookOpen }, { path: '/courses', label: 'Courses', icon: Library }];
export function AppShell() {
  const { user, signOut } = useAuth(); const navigate = useNavigate();
  const [search, setSearch] = useState(''); const [mobileOpen, setMobileOpen] = useState(false); const [notifications, setNotifications] = useState(false); const [accountOpen, setAccountOpen] = useState(false); const [logoutError, setLogoutError] = useState('');
  const activity = useResource(() => dashboardApi.get(), notifications ? 'open' : 'closed');
  const logout = async () => { try { await signOut(); navigate('/login'); } catch (e) { setLogoutError(e instanceof Error ? e.message : 'Unable to sign out.'); } };
  const submitSearch = (e: FormEvent) => { e.preventDefault(); navigate(`/students?q=${encodeURIComponent(search.trim())}`); setSearch(''); };
  return <div className="app-shell">
    {mobileOpen && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}
    <aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}><Brand /><span className="nav-label">MANAGEMENT</span><nav aria-label="Main navigation">{navigation.filter(item => user?.role !== 'STUDENT' || ['/dashboard', '/classes'].includes(item.path)).filter(item => user?.role !== 'LECTURER' || item.path !== '/lecturers').map(item => <NavLink key={item.path} to={item.path} onClick={() => setMobileOpen(false)} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><item.icon size={20} /><span>{item.label}</span></NavLink>)}<div className="nav-divider" /><NavLink to="/settings" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Settings size={20} /><span>Settings</span></NavLink></nav><div className="sidebar-bottom"><button className="sidebar-account" onClick={() => navigate('/settings')}><Avatar name={user?.displayName || 'Administrator'} /><span><strong>{user?.displayName}</strong><small>{user?.role === 'ADMIN' ? 'Administrator' : 'Lecturer'}</small></span><ChevronDown size={16} /></button></div></aside>
    <div className="main-layout"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={22} /></button><form onSubmit={submitSearch}><SearchInput placeholder="Search anything..." value={search} onChange={e => setSearch(e.target.value)} /></form><div className="topbar-right"><div className="popover-anchor"><button aria-label="Notifications" aria-expanded={notifications} className="icon-button notification-button" onClick={() => { setNotifications(v => !v); setAccountOpen(false); }}><Bell size={20} /><span className="notification-dot" /></button>{notifications && <section className="popover notifications"><div className="popover-title"><strong>Recent activity</strong><button className="icon-button" aria-label="Close notifications" onClick={() => setNotifications(false)}><X size={16} /></button></div>{activity.loading ? <p>Loading activity…</p> : activity.error ? <p>{activity.error}</p> : activity.data?.activities.slice(0, 5).map(a => <p key={a.id}>{a.message}<small>{new Date(a.createdAt).toLocaleString('en-GB')}</small></p>)}</section>}</div><span className="topbar-separator" /><div className="popover-anchor"><button className="topbar-account" onClick={() => { setAccountOpen(v => !v); setNotifications(false); }} aria-expanded={accountOpen}><span>{user?.role === 'ADMIN' ? 'Admin' : 'Lecturer'}</span><Avatar name={user?.displayName || 'Admin'} /><ChevronDown size={14} /></button>{accountOpen && <div className="popover account-menu"><button onClick={() => { navigate('/settings'); setAccountOpen(false); }}><Settings size={16} /> Account settings</button><button onClick={logout}><LogOut size={16} /> Sign out</button>{logoutError && <p className="field-error">{logoutError}</p>}</div>}</div></div></header><main className="content"><Outlet /></main><footer className="app-footer"><span>© {new Date().getFullYear()} Educare. University administration.</span><span>Student management workspace</span></footer></div>
  </div>;
}
