import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, GraduationCap, Pencil, Plus, Trash2, Users } from 'lucide-react';
import { classesApi } from '../api/class-info.api';
import { useAuth } from '../context/AuthContext';
import { useResource } from '../hooks/useResource';
import type { AcademicClass, ClassViewModel } from '../types';
import { Button, Card, EmptyState, ErrorState, PageHeader, SearchInput, Select } from '../components/ui';
import { ClassFormDrawer } from '../components/classes/ClassFormDrawer';
import { ConfirmDrawer } from '../components/ui/ConfirmDrawer';
export function ClassesPage() {
  const { canEdit, canDelete } = useAuth(); const resource = useResource(classesApi.getAll);
  const [search, setSearch] = useState(''); const [domain, setDomain] = useState(''); const [cohort, setCohort] = useState(''); const [sort, setSort] = useState('newest'); const [editing, setEditing] = useState<AcademicClass | 'new' | null>(null); const [deleting, setDeleting] = useState<ClassViewModel | null>(null);
  const domains = [...new Set(resource.data?.map(c => c.domain))]; const cohorts = [...new Set(resource.data?.map(c => c.cohort).filter(c => c !== null))].sort((a, b) => b - a);
  const filtered = (resource.data || []).filter(c => `${c.name} ${c.code} ${c.manager}`.toLowerCase().includes(search.toLowerCase()) && (!domain || c.domain === domain) && (!cohort || String(c.cohort) === cohort)).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : (b.academicId || 0) - (a.academicId || 0));
  return <><PageHeader title="Classes" description="Manage class information and student rosters." action={canEdit && <Button onClick={() => setEditing('new')}><Plus size={18} />Add class</Button>} /><div className="filters standalone-filters"><SearchInput placeholder="Search classes..." value={search} onChange={e => setSearch(e.target.value)} /><Select aria-label="Filter class domain" value={domain} onChange={e => setDomain(e.target.value)}><option value="">Domain: All</option>{domains.map(d => <option key={d}>{d}</option>)}</Select><Select aria-label="Filter enrollment year" value={cohort} onChange={e => setCohort(e.target.value)}><option value="">Enrollment: All</option>{cohorts.map(c => <option key={c} value={c}>Enrollment: {c}</option>)}</Select><Select aria-label="Sort classes" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Sort: Newest</option><option value="name">Sort: Name</option></Select></div>{resource.error ? <ErrorState message={resource.error} retry={resource.reload} /> : <div className="entity-grid">{resource.loading ? Array.from({ length: 6 }, (_, i) => <Card key={i}><div className="skeleton entity-skeleton" /></Card>) : filtered.map(c => <Card className="class-card" key={c.id}><div className="class-card-top"><Link to={`/classes/${c.id}`} className="class-icon"><BookOpen size={23} /></Link><span className="domain-badge">{c.domain === 'Information Technology' ? 'IT' : c.domain}</span><div className="row-actions">{canEdit && c.metadata && <button className="icon-button" aria-label={`Edit ${c.name}`} onClick={() => setEditing(c.metadata || null)}><Pencil size={15} /></button>}{canDelete && c.academicId && <button className="icon-button danger-hover" aria-label={`Delete ${c.name}`} onClick={() => setDeleting(c)}><Trash2 size={15} /></button>}</div></div><Link className="entity-title" to={`/classes/${c.id}`}><h3>{c.name}</h3></Link><p className="class-code">{c.code} <span>·</span> {c.cohort || 'Enrollment not set'}</p><div className="class-card-meta"><span><Users size={15} />{c.studentCount === null ? 'Roster unavailable' : `${c.studentCount} students`}</span><span><GraduationCap size={15} />{c.manager}</span></div><div className="class-card-footer"><Link to={`/classes/${c.id}`}>View class<ArrowRight size={15} /></Link>{c.metadata && <span>{c.metadata.capacity} max.</span>}</div></Card>)}</div>}{!resource.loading && !resource.error && filtered.length === 0 && <Card><EmptyState title="No classes found." /></Card>}{editing && <ClassFormDrawer record={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSaved={resource.reload} />}{deleting?.academicId && <ConfirmDrawer name={deleting.name} onDelete={() => classesApi.delete(deleting.academicId!)} onClose={() => setDeleting(null)} onSaved={resource.reload} />}</>;
}
