import { useState } from 'react';
import { BookOpen, Pencil, Plus, Trash2 } from 'lucide-react';
import { coursesApi, lecturersApi } from '../api/management.api';
import { useAuth } from '../context/AuthContext';
import { useResource } from '../hooks/useResource';
import type { Course } from '../types';
import { Button, Card, DataTable, PageHeader, Pagination, SearchInput, Select, type Column } from '../components/ui';
import { RecordDrawer } from '../components/ui/RecordDrawer';
import { ConfirmDrawer } from '../components/ui/ConfirmDrawer';
export function CoursesPage() {
  const resource = useResource(coursesApi.list); const lecturers = useResource(lecturersApi.list); const { canEdit, canDelete } = useAuth();
  const [search, setSearch] = useState(''); const [faculty, setFaculty] = useState(''); const [credits, setCredits] = useState(''); const [sort, setSort] = useState('code'); const [direction, setDirection] = useState('ASC'); const [page, setPage] = useState(0); const [editing, setEditing] = useState<Course | 'new' | null>(null); const [deleting, setDeleting] = useState<Course | null>(null);
  const filtered = (resource.data || []).filter(c => `${c.name} ${c.code} ${c.lecturer || ''}`.toLowerCase().includes(search.toLowerCase()) && (!faculty || c.faculty === faculty) && (!credits || String(c.credits) === credits)).sort((a, b) => { const comparison = sort === 'credits' ? a.credits - b.credits : (sort === 'name' ? a.name : a.code).localeCompare(sort === 'name' ? b.name : b.code); return direction === 'ASC' ? comparison : -comparison; });
  const changeSort = (key: string) => { setDirection(sort === key && direction === 'ASC' ? 'DESC' : 'ASC'); setSort(key); setPage(0); };
  const columns: Column<Course>[] = [{ key: 'name', title: 'Course', sortable: true, render: c => <div className="course-cell"><span className="class-icon"><BookOpen size={17} /></span><strong>{c.name}</strong></div> }, { key: 'code', title: 'Code', sortable: true, render: c => <span className="code-text">{c.code}</span> }, { key: 'credits', title: 'Credits', sortable: true, render: c => <span className="credit-badge">{c.credits} credits</span> }, { key: 'faculty', title: 'Faculty', render: c => c.faculty === 'Information Technology' ? 'IT' : c.faculty }, { key: 'lecturer', title: 'Lecturer', render: c => c.lecturer || 'Unassigned' }, ...(canEdit ? [{ key: 'actions', title: 'Actions', render: (c: Course) => <div className="row-actions"><button className="icon-button" aria-label={`Edit ${c.name}`} onClick={() => setEditing(c)}><Pencil size={15} /></button>{canDelete && <button className="icon-button danger-hover" aria-label={`Delete ${c.name}`} onClick={() => setDeleting(c)}><Trash2 size={15} /></button>}</div> }] : [])];
  return <><PageHeader title="Courses" description="Manage course catalog, credits and assigned lecturers." action={canEdit && <Button onClick={() => setEditing('new')}><Plus size={18} />Add course</Button>} /><Card className="table-card"><div className="filters"><SearchInput placeholder="Search courses..." value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /><Select aria-label="Filter courses by faculty" value={faculty} onChange={e => { setFaculty(e.target.value); setPage(0); }}><option value="">Faculty: All</option>{[...new Set(resource.data?.map(c => c.faculty))].map(f => <option key={f}>{f}</option>)}</Select><Select aria-label="Filter by credits" value={credits} onChange={e => { setCredits(e.target.value); setPage(0); }}><option value="">Credits: All</option>{[...new Set(resource.data?.map(c => c.credits))].sort((a, b) => a - b).map(c => <option key={c} value={c}>{c} credits</option>)}</Select><Select aria-label="Sort courses" value={sort} onChange={e => { setSort(e.target.value); setPage(0); }}><option value="code">Sort: Code</option><option value="name">Sort: Name</option><option value="credits">Sort: Credits</option></Select></div><DataTable columns={columns} rows={filtered.slice(page * 8, (page + 1) * 8)} rowKey={c => c.id} loading={resource.loading} error={resource.error} retry={resource.reload} sort={sort} onSort={changeSort} /><Pagination page={page} total={filtered.length} entity="courses" onPage={setPage} /></Card>{editing && <RecordDrawer title={editing === 'new' ? 'Add course' : 'Edit course'} subtitle="Manage course catalog information." fields={[{ key: 'name', label: 'Course name', required: true }, { key: 'code', label: 'Course code', required: true, maxLength: 30 }, { key: 'credits', label: 'Credits', type: 'number', required: true, min: 1, max: 10 }, { key: 'faculty', label: 'Faculty', required: true }, { key: 'lecturerId', label: 'Assigned lecturer', type: 'select', options: [{ value: '', label: 'Unassigned' }, ...(lecturers.data || []).map(l => ({ value: String(l.id), label: l.name }))] }]} initial={editing === 'new' ? { name: '', code: '', credits: '3', faculty: 'Information Technology', lecturerId: '' } : { name: editing.name, code: editing.code, credits: String(editing.credits), faculty: editing.faculty, lecturerId: String(editing.lecturerId || '') }} onSave={v => coursesApi.save(editing === 'new' ? undefined : editing.id, { name: v.name, code: v.code, faculty: v.faculty, credits: Number(v.credits), lecturerId: v.lecturerId ? Number(v.lecturerId) : null })} onSaved={resource.reload} onClose={() => setEditing(null)} />}{deleting && <ConfirmDrawer name={deleting.name} onDelete={() => coursesApi.delete(deleting.id)} onSaved={resource.reload} onClose={() => setDeleting(null)} />}</>;
}
