import { useState, type FormEvent } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, GraduationCap, LockKeyhole, Users } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { Brand } from '../components/layout/AppShell';
import { Button, Field, Input } from '../components/ui';
export function LoginPage() {
  const { user, signIn } = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [remember, setRemember] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/dashboard" replace />;
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); setBusy(true); try { await signIn(email, password, remember); navigate('/dashboard'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to sign in. Check the server connection.'); } finally { setBusy(false); } };
  return <div className="login-page"><section className="login-showcase"><div className="login-brand"><Brand /></div><div className="showcase-card"><span className="showcase-mark"><GraduationCap size={35} /></span><h1>Student management<br />made simple.</h1><p>A clean workspace for students, classes,<br />lecturers and courses.</p><div className="showcase-preview"><div className="preview-header"><span className="preview-dot" /><span className="preview-line" /><span className="preview-line short" /></div><div className="preview-content"><div className="preview-sidebar">{[1, 2, 3, 4].map(n => <span key={n} className={n === 1 ? 'selected' : ''} />)}</div><div className="preview-main"><div className="preview-stats">{[Users, GraduationCap, LockKeyhole].map((Icon, i) => <span key={i}><Icon size={15} /><i /><i /></span>)}</div><div className="preview-chart">{[44, 76, 58, 91, 66, 38].map((height, i) => <span key={i} style={{ height: `${height}%` }} />)}</div></div></div></div><p className="showcase-preview-label">Workspace preview</p><div className="showcase-bottom" aria-label="Example workspace statistics"><span><strong>1,248</strong>Students</span><span><strong>42</strong>Classes</span><span><strong>87</strong>Lecturers</span></div></div><p className="showcase-footer">One workspace. A clearer academic journey.</p></section><section className="login-form-panel"><form className="login-form" onSubmit={submit}><span className="login-form-icon"><GraduationCap size={24} /></span><h1>Welcome back</h1><p>Sign in to continue to Educare.</p>{error && <div className="form-error" role="alert">{error}</div>}<Field label="Email"><Input type="email" autoComplete="username" required value={email} placeholder="you@university.edu.vn" onChange={e => setEmail(e.target.value)} /></Field><Field label="Password"><div className="password-input"><Input required type={show ? 'text' : 'password'} autoComplete="current-password" value={password} placeholder="Enter your password" onChange={e => setPassword(e.target.value)} /><button type="button" className="icon-button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(v => !v)}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></Field><label className="remember-me"><input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)} />Remember me</label><Button className="login-submit" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}<ArrowRight size={17} /></Button><p className="login-footnote"><LockKeyhole size={14} />Use your university account to access the system.</p></form><p className="login-bottom">Educare · University administration</p></section></div>;
}
