import { useState, type FormEvent } from 'react';
import { authApi } from '../api/auth.api';
import { useAuth } from '../context/AuthContext';
import { Avatar, Button, Card, Field, Input, PageHeader } from '../components/ui';
export function SettingsPage() {
  const { user, signOut } = useAuth(); const [current, setCurrent] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); setMessage(''); if (password !== confirm) { setError('New passwords do not match.'); return; } setBusy(true); try { await authApi.changePassword(current, password); setCurrent(''); setPassword(''); setConfirm(''); setMessage('Password updated successfully.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update password.'); } finally { setBusy(false); } };
  return <><PageHeader title="Settings" description="Manage your account and security preferences." /><div className="settings-grid"><Card><h2>Account profile</h2><div className="settings-profile"><Avatar size="large" name={user?.displayName || 'Admin'} /><h3>{user?.displayName}</h3><p>{user?.username}</p><span className="domain-badge">{user?.role === 'ADMIN' ? 'Administrator' : 'Lecturer'}</span></div><Button variant="secondary" onClick={() => signOut().catch(e => setError(e instanceof Error ? e.message : 'Unable to sign out.'))}>Sign out</Button></Card><Card><h2>Change password</h2><p className="muted">Use at least 8 characters for your new password.</p><form className="settings-form" onSubmit={submit}>{error && <p role="alert" className="form-error">{error}</p>}{message && <p role="status" className="success-message">{message}</p>}<Field label="Current password"><Input required type="password" autoComplete="current-password" value={current} onChange={e => setCurrent(e.target.value)} /></Field><Field label="New password"><Input required type="password" minLength={8} maxLength={72} autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} /></Field><Field label="Confirm new password"><Input required type="password" autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} /></Field><Button disabled={busy}>{busy ? 'Saving…' : 'Save password'}</Button></form></Card></div></>;
}
