import { useEffect, useId, useRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react';
import { ArrowDownUp, ChevronLeft, ChevronRight, Search, X, Users, AlertCircle } from 'lucide-react';
import type { Status } from '../../types';

export function Button({ variant = 'primary', className = '', children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' | 'text'; children: ReactNode }) { return <button className={`btn btn-${variant} ${className}`} {...props}>{children}</button>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`input ${props.className || ''}`} />; }
export function Select({ children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={`input select ${props.className || ''}`}>{children}</select>; }
export function SearchInput({ placeholder, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <div className="search-input"><Search size={18} /><Input aria-label={placeholder} placeholder={placeholder} {...props} /></div>; }
export function Avatar({ name, size = 'normal', tone }: { name: string; size?: 'small' | 'normal' | 'large'; tone?: string }) { const initial = name.trim().split(/\s+/).map(n => n[0]).filter(Boolean).slice(-2).join(''); const palette = ['indigo', 'mint', 'amber', 'blue']; return <span aria-hidden="true" className={`avatar avatar-${size} avatar-${tone || palette[name.charCodeAt(0) % palette.length]}`}>{initial}</span>; }
export function StatusBadge({ status }: { status: Status }) { const label = { ACTIVE: 'Active', PENDING: 'Pending', INACTIVE: 'Inactive' }[status]; return <span className={`status status-${status.toLowerCase()}`}><span />{label}</span>; }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
export function StatCard({ label, value, caption, icon }: { label: string; value: string | number; caption: string; icon: ReactNode }) { return <Card className="stat-card"><div className="stat-top"><span>{label}</span><span className="stat-icon">{icon}</span></div><strong>{typeof value === 'number' ? value.toLocaleString('en-US') : value}</strong><p>{caption}</p></Card>; }
export function PageHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <header className="page-header"><div><h1>{title}</h1><p>{description}</p></div>{action}</header>; }
export function EmptyState({ title = 'No records found.', message = 'Try changing your filters.', action }: { title?: string; message?: string; action?: ReactNode }) { return <div className="empty-state"><span className="empty-icon"><Users size={26} /></span><h3>{title}</h3><p>{message}</p>{action}</div>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div role="alert" className="error-state"><AlertCircle size={22} /><p>{message}</p><Button variant="secondary" onClick={retry}>Retry</Button></div>; }
export function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small className="field-error">{error}</small>}</label>; }
export function Drawer({ title, subtitle, children, onClose }: { title: string; subtitle: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null); const titleId = useId();
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { dialog?.close(); document.body.style.overflow = overflow; }; }, []);
  return <dialog ref={ref} className="drawer" aria-labelledby={titleId} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === ref.current && e.clientX < (ref.current?.getBoundingClientRect().left || 0)) onClose(); }}><header className="drawer-header"><div><h2 id={titleId}>{title}</h2><p>{subtitle}</p></div><button className="icon-button" aria-label="Close drawer" onClick={onClose}><X size={20} /></button></header>{children}</dialog>;
}
export interface Column<T> { key: string; title: string; render: (row: T) => ReactNode; sortable?: boolean; className?: string }
export function DataTable<T>({ columns, rows, rowKey, onRowClick, loading, error, retry, sort, onSort, emptyTitle, emptyMessage }: { columns: Column<T>[]; rows: T[]; rowKey: (row: T) => string | number; onRowClick?: (row: T) => void; loading?: boolean; error?: string; retry?: () => void; sort?: string; onSort?: (key: string) => void; emptyTitle?: string; emptyMessage?: string }) {
  if (error) return <ErrorState message={error} retry={retry || (() => {})} />;
  return <div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(c => <th key={c.key} className={c.className}>{c.sortable ? <button className={sort === c.key ? 'sort-active' : ''} onClick={() => onSort?.(c.key)}>{c.title}<ArrowDownUp size={13} /></button> : c.title}</th>)}</tr></thead><tbody>{loading ? Array.from({ length: 8 }, (_, i) => <tr key={i}>{columns.map(c => <td key={c.key}><span className="skeleton" /></td>)}</tr>) : rows.map(row => <tr key={rowKey(row)} className={onRowClick ? 'clickable-row' : ''} tabIndex={onRowClick ? 0 : undefined} onClick={() => onRowClick?.(row)} onKeyDown={e => { if (e.key === 'Enter' && e.target === e.currentTarget) onRowClick?.(row); }}>{columns.map(c => <td key={c.key} className={c.className}>{c.render(row)}</td>)}</tr>)}</tbody></table>{!loading && rows.length === 0 && <EmptyState title={emptyTitle} message={emptyMessage} />}</div>;
}
export function Pagination({ page, total, size = 8, entity, onPage }: { page: number; total: number; size?: number; entity: string; onPage: (page: number) => void }) {
  const pages = Math.max(1, Math.ceil(total / size));
  const visible = Array.from(new Set([0, page - 1, page, page + 1, pages - 1].filter(p => p >= 0 && p < pages))).sort((a, b) => a - b);
  return <footer className="pagination"><p>Showing <strong>{total ? page * size + 1 : 0}–{Math.min((page + 1) * size, total)}</strong> of <strong>{total.toLocaleString('en-US')}</strong> {entity}</p><div><button aria-label="Previous page" disabled={page === 0} onClick={() => onPage(page - 1)}><ChevronLeft size={16} /></button>{visible.map((p, i) => <span key={p}>{i > 0 && p - visible[i - 1] > 1 && <span className="pagination-gap">…</span>}<button aria-label={`Page ${p + 1}`} aria-current={page === p ? 'page' : undefined} className={page === p ? 'active' : ''} onClick={() => onPage(p)}>{p + 1}</button></span>)}<button aria-label="Next page" disabled={page >= pages - 1} onClick={() => onPage(page + 1)}><ChevronRight size={16} /></button></div></footer>;
}
