import { useState, type FormEvent } from 'react';
import { ApiError } from '../../api/client';
import { Button, Drawer, Field, Input, Select } from './index';
export interface FormField { key: string; label: string; type?: 'text' | 'email' | 'tel' | 'number' | 'select'; required?: boolean; min?: number; max?: number; step?: number; maxLength?: number; options?: { value: string; label: string }[] }
export function RecordDrawer({ title, subtitle, fields, initial, onSave, onClose, onSaved }: { title: string; subtitle: string; fields: FormField[]; initial: Record<string, string>; onSave: (values: Record<string, string>) => Promise<unknown>; onClose: () => void; onSaved: () => void }) {
  const [values, setValues] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [errors, setErrors] = useState<Record<string, string>>({});
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { await onSave(values); onSaved(); onClose(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save record.'); if (e instanceof ApiError) setErrors(e.fields); } finally { setBusy(false); } };
  return <Drawer title={title} subtitle={subtitle} onClose={onClose}><form className="drawer-form" onSubmit={submit}><div className="drawer-body">{error && <p role="alert" className="form-error">{error}</p>}{fields.map(f => <Field key={f.key} label={f.label} error={errors[f.key]}>{f.type === 'select' ? <Select required={f.required} value={values[f.key] || ''} onChange={e => setValues(v => ({ ...v, [f.key]: e.target.value }))}>{f.options?.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</Select> : <Input required={f.required} type={f.type || 'text'} value={values[f.key] || ''} min={f.min} max={f.max} step={f.step} maxLength={f.maxLength || 120} onChange={e => setValues(v => ({ ...v, [f.key]: e.target.value }))} />}</Field>)}</div><div className="drawer-footer"><Button type="button" variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</Button></div></form></Drawer>;
}
